name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: |
          npm run build:production
          cp .htaccess dist/wahlrecht-frontend/
      - name: Copy files to remote
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -az -r --del
          path: dist/wahlrecht-frontend/.
          remote_path: ~/tmp/build
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
      - name: Activate new files
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            shopt -s dotglob
            rm -rf tmp/old.build
            mkdir tmp/old.build
            cp -r html/* tmp/old.build/
            rm -rf html/*
            cp -r tmp/build/* html/
            rm -rf tmp/build

